### ISSUE TITLE
Getting Error on running lightningd on C-Lightning Mainnet Netwrok

### ISSUE THREAD

**Issue by Dhara-Openxcell** [cdecker/lightning-integration#12]
I have successfully synced with the bitcoind chain . But when try to run lightningd command ,I am getting following issue:
As referred to the article on    https://medium.com/@dougvk/run-your-own-mainnet-lightning-node-2d2eab628a8b 

root@Admin:~# docker run — rm — name lightning — network container:bitcoind_mainnet -v /scratch/bitcoin/mainnet/bitcoind:/root/.bitcoin -v /scratch/bitcoin/mainnet/clightning:/root/.lightning — entrypoint /usr/bin/lightningd cdecker/lightningd:master — network=bitcoin — log-level=debug
Unable to find image ‘cdecker/lightningd:master’ locallydocker: Error response from daemon: manifest for cdecker/lightningd:master not found.See ‘docker run — help’.

**Comment by cdecker** [comment]
Not really the correct repo, that'd be cdecker/dockerfiles. The issue is easy to fix though, just replace `cdecker/lightningd:master` with `cdecker/lightningd:latest` :wink:
