### ISSUE TITLE
Not working with virtualenv

### ISSUE THREAD

**Issue by mecampbellsoup** [cdecker/lightning-integration#14]
First I ran `virtualenv -p python3 venv` to install dependencies locally into `venv/`. Then, `source venv/bin/activate`.

However, trying to run `py.test` fails as follows:

```
15:18:11 › py.test -v test.py

zsh: /usr/local/bin/py.test: bad interpreter: /usr/local/opt/python3/bin/python3.5: no such file or directory
(venv)

15:18:14 › python --version
Python 3.6.4
(venv)
```
Anything stand out in here? Thanks.

**Comment by mecampbellsoup** [comment]
The `python3.5` thing looks wrong, considering my local version is 3.6.4...

**Comment by cdecker** [comment]
Besides creating a virtualenv, you also need to install the required dependencies:

```
pip install -r requirements.txt
```

That will install py.test in your venv and use the correct python version.
