### ISSUE TITLE
c-lightning unable to de-obfuscate lnd onion

### ISSUE THREAD

**Issue by cdecker** [cdecker/lightning-integration#4]
c-lightning is failing to decode the routing onion if the onion is build by lnd:

```
state = <grpc._channel._RPCState object at 0x7f91cf6a35f8>
call = <grpc._cython.cygrpc.Call object at 0x7f91cf6a3668>, with_call = False
deadline = None

    def _end_unary_response_blocking(state, call, with_call, deadline):
        if state.code is grpc.StatusCode.OK:
            if with_call:
                rendezvous = _Rendezvous(state, call, None, deadline)
                return state.response, rendezvous
            else:
                return state.response
        else:
>           raise _Rendezvous(state, None, None, deadline)
E           grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, unable to route payment to destination: TemporaryChannelFailure: unable to de-obfuscate onion failure, htlc with hash(ad70987ab10ad6b18e33cfdb944a5c60cadeb771dccc06bd93a34a3498254676): unable to decode error update: EOF)>

.direnv/python-3.5.2/lib/python3.5/site-packages/grpc/_channel.py:455: _Rendezvous
```

Full logs [here](https://gist.github.com/anonymous/b6e11039ab0d5db79ac92631cd5e92f5). Rather strange that c-lightning is complaining about an incorrect CLTV value in [L2712](https://gist.github.com/anonymous/b6e11039ab0d5db79ac92631cd5e92f5#file-c-lightning-lnd-onion-fail-log-L2712), and somehow that gets translated into an onion problem.

**Comment by cdecker** [comment]
Ping @rustyrussell and @Roasbeef

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> Full logs [here](https://gist.github.com/anonymous/b6e11039ab0d5db79ac92631cd5e92f5). Rather strange that c-lightning is complaining about an incorrect CLTV value in [L2712](https://gist.github.com/anonymous/b6e11039ab0d5db79ac92631cd5e92f5#file-c-lightning-lnd-onion-fail-log-L2712), and somehow that gets translated into an onion problem.

No, it's because you're not using the routing-final-cltv branch, which
is not so strict about cltv_delta.

master expects an exact delta of 6.

Cheers,
Rusty.

**Comment by cdecker** [comment]
Yep, I was thinking more about the misleading error message, and I don't know which one of us is getting the wires crossed. Since eclair and lightning both fail the same way I'm tempted to point to `lnd`

**Comment by cdecker** [comment]
Error is gone :+1:
