### ISSUE TITLE
Dockerfile seems broken

### ISSUE THREAD

**Issue by jtimon** [cdecker/lightning-integration#59]
I'm trying: 
```
docker build --tag=lnintegration . && docker run lnintegration
```

I'm getting the following error:

```
go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.0.0
go: verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0: checksum mismatch
	downloaded: h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=
	go.sum:     h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
```

I'm using the branch in https://github.com/cdecker/lightning-integration/pull/60

**Comment by cdecker** [comment]
I remember coming across a similar issue before. It seems to me like one of the dependencies of `lnd` changed somehow, resulting in non-matching hashes.

Maybe @Roasbeef knows what to do in these cases?

**Comment by cdecker** [comment]
Quickly discussed this with @Roasbeef on their slack:

![Selection_027](https://user-images.githubusercontent.com/120117/61665707-fe8a5180-acd5-11e9-8b6a-041333594786.png)
