### ISSUE TITLE
Eclair fails to parse c-lightning bolt11 payment requests

### ISSUE THREAD

**Issue by cdecker** [cdecker/lightning-integration#6]
After migrating to the BOLT11 style payment requests for payments (65f8689470124d0575efd5218f7ef60be18ca2ee), eclair complains somewhere about the payment request:

```
E           ValueError: Server returned an unknown error: 500 ({
E             "result" : null,
E             "error" : {
E               "code" : -1,
E               "message" : "24 (of class java.lang.Byte)"
E             },
E             "id" : "scala-client"
E           })
```

This error occurs when passing a payment request generated by c-lightning to the `send` RPC call of eclair:

```
        amount = int(capacity / 10)
        req = node2.invoice(amount)
>       payment_key = node1.send(req)
```

Full log can be found [here](https://gist.github.com/anonymous/89eb5aad9837acf2f268115dfd9f31e9)

**Comment by cdecker** [comment]
Ping @sstone, @cdecker & @rustyrussell

**Comment by pm47** [comment]
This must be related to the support of `min_final_cltv_expiry` field, which has been merged yesterday afternoon into eclair (commit https://github.com/ACINQ/eclair/commit/e17335931b6220c085a12b3e4292bb4d7cfc54d9). Starting from this commit eclair can parse the payment request.

**Comment by cdecker** [comment]
Ok will update and see if things change, thanks for the quick feedback

**Comment by pm47** [comment]
Just realized my message was unclear: I was able to reproduce the error with an older version of eclair and made sure that the issue disappears after commit https://github.com/ACINQ/eclair/commit/e17335931b6220c085a12b3e4292bb4d7cfc54d9.

So things will definitely change if you update ;-)

**Comment by cdecker** [comment]
I can confirm that this was fixed, thanks ^^

**Comment by rustyrussell** [comment]
Note: you *should* be ignoring unknown fields!!!

**Comment by pm47** [comment]
True. Appending to the TODO list!
