### ISSUE TITLE
Eclair ignores `announcement_signatures` sent by lnd

### ISSUE THREAD

**Issue by pm47** [cdecker/lightning-integration#8]
It appears that `lnd` sends the `announcement_signatures` message right after `funding_locked`, whereas `eclair` expects it after having sent and received the `funding_locked`. Eclair currently drops the `announcement_signatures` if it hasn't sent the `funding_locked`.

`lnd`'s behavior is correct wrt to [BOLT 7](https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#requirements) and `eclair`'s is not, but I wonder if the spec should instead say:

> "If sent, announcement_signatures messages MUST NOT be sent until funding_locked has been sent **and received**, and the funding transaction has at least 6 confirmations."

I think it makes sense to exchange announcement-related messages only after both parties agree that the channel is ready, we already have that barrier for `update_*` messages, and that would remove the need to stash messages (which probably only occurs during testing when we generate blocks by bulk).

OTOH it does break the freeze, even if that's a simple change. I already discussed this with @cdecker, what do you think @Roasbeef and @rustyrussell?

**Comment by cdecker** [comment]
I think this is causing the problems that I see in the following tests:

1. [test_forwarded_payment[eclair_eclair_lnd]](https://gist.github.com/517f871602e0686ca1492c90653b1651)
1. [test_forwarded_payment[lightning_eclair_lnd]](https://gist.github.com/9ec03c49c5cffdbb9a422fd5827bdc11
)
1. [test_forwarded_payment[lnd_eclair_lnd]](https://gist.github.com/9d2b66ddfcd0975693cc99f915b25625
)

In all of these cases `eclair` is in the middle and opens a channel to `lnd` and the first node fails to find a route.

**Comment by pm47** [comment]
Confirmed, it is the same issue in all those tests.

**Comment by rustyrussell** [comment]
Will change c-lightning to defer sending, independent of spec change.  I think it's just saner.

**Comment by pm47** [comment]
Starting from commit https://github.com/ACINQ/eclair/commit/fcb5bf2549c0c4ab8391b607c99c33429f39178e eclair stashes the `announcement_signatures` if they are received early. This fixes the 3 remaining tests 🎉.

I think we should leave the spec as-is, since if early-send of `announcement_signatures` is allowed then everybody MUST support it.

**Comment by cdecker** [comment]
Yeah, great work @pm47 and @sstone, I'll run the tests again once the htlckey change is in and hopefully get a sea of green :tada:
