### ISSUE TITLE
[TRIAGE] New failures following the fee computations

### ISSUE THREAD

**Issue by cdecker** [cdecker/lightning-integration#9]
The changes in fee estimation seems to cause quite a few new failures. Here's the list of failing tests, some of the may just be flakes, and I guess most of them are caused by crazy fee-estimation on regtest.

 1. ~[test_direct_payment-eclair_lightning.log](https://gist.github.com/fc904ea991c56b3a2814b77cb97b6de0)~
 1. ~[test_direct_payment-lightning_eclair.log](https://gist.github.com/553be68320920426d19c7fb770ed8e36)~
 1. [test_direct_payment-lnd_eclair.log](https://gist.github.com/9b55e183c8875a9534b232a420bf0670)
 1. [test_direct_payment-lnd_lightning.log](https://gist.github.com/7d3119da4ef17707a4278d5a537f07fd)
 1. [test_forwarded_payment-eclair_lightning_eclair.log](https://gist.github.com/59399874fe8accb25ceb1e2fbb103eaf)
 1. [test_forwarded_payment-eclair_lightning_lightning.log](https://gist.github.com/94dbfb000359df010465c42bf034c5ee)
 1. [test_forwarded_payment-eclair_lnd_eclair.log](https://gist.github.com/dab468094441cb73ab1efd3db298b693)
 1. [test_forwarded_payment-eclair_lnd_lightning.log](https://gist.github.com/0d7612e2ea32bb1c2be3cd94b213fd1e)
 1. [test_forwarded_payment-lightning_eclair_lightning.log](https://gist.github.com/5ed313096b09a71b4c72df7c0376e4a2)
 1. [test_forwarded_payment-lightning_lightning_eclair.log](https://gist.github.com/047b477ab624e246124b093f46849d00)
 1. [test_forwarded_payment-lightning_lnd_eclair.log](https://gist.github.com/b19dddff5a863427c8d9a0347ea66e44)
 1. [test_forwarded_payment-lnd_eclair_eclair.log](https://gist.github.com/570cbb7ffcbcfb1fe518008a6ef31901)
 1. [test_forwarded_payment-lnd_eclair_lightning.log](https://gist.github.com/068c72700303b9ead8162852bd430817)
 1. [test_forwarded_payment-lnd_eclair_lnd.log](https://gist.github.com/b0b2a31acf22ab16a3974e310c469146)
 1. [test_forwarded_payment-lnd_lightning_eclair.log](https://gist.github.com/1c3fabc1ed535abfea817ea8aa590052)
 1. [test_forwarded_payment-lnd_lightning_lightning.log](https://gist.github.com/b5f5ab7c8b7f1f16278db1078bbdcda2)
 1. [test_forwarded_payment-lnd_lightning_lnd.log](https://gist.github.com/2e89633518640a9f6e0332b072a5bd65)
 1. [test_forwarded_payment-lnd_lnd_eclair.log](https://gist.github.com/0e502ab24029c10464d98e299aef6989)
 1. [test_forwarded_payment-lnd_lnd_lightning.log](https://gist.github.com/b1455da6efbc63c27519df9d4a082b55)
 1. [test_gossip-lightning_eclair.log](https://gist.github.com/82621a20375ffdaf01a1093629fbd1b8)
 1. [test_open_channel-lnd_eclair.log](https://gist.github.com/193cde4ee1dfa4dcd44eb097bc0f5177)
 1. [test_open_channel-lnd_lightning.log](https://gist.github.com/8d574242420e33a4bb6116d4e6c0eb00)
 1. [test_reconnect-lnd_eclair.log](https://gist.github.com/d272ae1f6659b40b21f9657dda218847)
 1. [test_reconnect-lnd_lightning.log](https://gist.github.com/dc89dfb651d02b70af7b3ad6d428cede)

Pretty sure at least nr. 20 is a flake. Will rerun to confirm :-)

**Comment by cdecker** [comment]
Ping @Roasbeef, @rustyrussell, @pm47, @sstone ^^

**Comment by Roasbeef** [comment]
On the `lnd -> c-lightning` funding, looks like they rejected our funding request due to insufficient fees: 
```
EBUG:lnd(16331):2017-11-29 17:25:34.567 [DBG] PEER: Received Error(chan_id=d67e295044505c21108475d67babe5734992e85236a5b52eb859e5d002b83962, err=[102 101 101 114 97 116 101 95 112 101 114 95 107 119 32 54 48 48 48 32 98 101 108 111 119 32 109 105 110 105 109 117 109 32 49 48 48 48 48 0]) from 127.0.0.1:16332
DEBUG:proc:lightning_openingd(2795): STATUS_FAIL_PEER_BAD: feerate_per_kw 6000 below minimum 10000
D
```

**Comment by Roasbeef** [comment]
Seems if I just double our hard coded fee rate (no estimation) then most of those will go away?

**Comment by Roasbeef** [comment]
Same thing with funding to `eclair`: 
```
DEBUG:lnd(16331):2017-11-29 17:23:47.647 [DBG] PEER: Received Error(chan_id=bc2357ff6dd8b7497ba3e886d2a9772c2d3d4fa5ac31455830344edee538e249, err=[108 111 99 97 108 47 114 101 109 111 116 101 32 102 101 101 114 97 116 101 115 32 97 114 101 32 116 111 111 32 100 105 102 102 101 114 101 110 116 58 32 114 101 109 111 116 101 70 101 101 114 97 116 101 80 101 114 75 119 61 54 48 48 48 32 108 111 99 97 108 70 101 101 114 97 116 101 80 101 114 75 119 61 53 51 55 54 48]) from 127.0.0.1:16332
DEBUG:lnd(16331):2017-11-29 17:23:47.647 [TRC] PEER: readMessage from 127.0.0.1:16332: (*lnwire.Error)(0xc420138380)({
DEBUG:lnd(16331): ChanID: (lnwire.ChannelID) (len=32 cap=32) bc2357ff6dd8b7497ba3e886d2a9772c2d3d4fa5ac31455830344edee538e249,
DEBUG:lnd(16331): Data: (lnwire.ErrorData) (len=88 cap=88) {
DEBUG:lnd(16331):  00000000  6c 6f 63 61 6c 2f 72 65  6d 6f 74 65 20 66 65 65  |local/remote fee|
DEBUG:lnd(16331):  00000010  72 61 74 65 73 20 61 72  65 20 74 6f 6f 20 64 69  |rates are too di|
DEBUG:lnd(16331):  00000020  66 66 65 72 65 6e 74 3a  20 72 65 6d 6f 74 65 46  |fferent: remoteF|
DEBUG:lnd(16331):  00000030  65 65 72 61 74 65 50 65  72 4b 77 3d 36 30 30 30  |eeratePerKw=6000|
DEBUG:lnd(16331):  00000040  20 6c 6f 63 61 6c 46 65  65 72 61 74 65 50 65 72  | localFeeratePer|
DEBUG:lnd(16331):  00000050  4b 77 3d 35 33 37 36 30                           |Kw=53760|
DEBUG:lnd(16331): }
DEBUG:lnd(16331):})
DEBUG:lnd(16331):
DEBUG:lnd(16331):2017-11-29 17:23:47.647 [ERR] FNDG: Received funding error from 0216a00f15d22a565e9064e16a3a6827fbd36099ee28a5d86bbdee4081b6be4b9d: unknown error
DEBUG:lnd(16331):2017-11-29 17:23:47.647 [INF] FNDG: Cancelling funding reservation for node_key=0216a00f15d22a565e9064e16a3a6827fbd36099ee28a5d86bbdee4081b6be4b9d, chan_id=bc2357ff6dd8b7497ba3e886d2a9772c2d3d4fa5ac31455830344edee538e249
DEBUG:lnd(16331):2017-11-29 17:23:47.647 [ERR] RPCS: unable to open channel to identityPub() nor peerID(1): rpc error: code = Code(208) desc = unknown error
```

**Comment by cdecker** [comment]
> Seems if I just double our hard coded fee rate (no estimation) then most of those will go away?

Yep, I tried adjusting c-lightning to lnd which added failures with eclair :-)

We should be able to meet somewhere in the middle, but I don't know what the value should be ;-)
